library:
  source-dirs: src
tests:
  Embers-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Embers
copyright: 2020 Syed Moiz Ur Rehman
maintainer: syedmoizurrehman@hotmail.com
dependencies:
- flow
- directory
- speculate
- MissingH
- extra
- mtl
- transformers
- containers
- base >= 4.7 && < 5
- hspec
- QuickCheck
- optparse-applicative
- semigroups
- pretty-simple
name: Embers
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Syed Moiz Ur Rehman
github: haze-lang/Embers
license: GPL-3.0-or-later
executables:
  Embers:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Embers
description: Please see the README on GitHub at <https://github.com/haze-lang/Embers#readme>
